name: Build GH pages
on:
    push:
        branches:
            - master
jobs:
    Build_Staging:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20.9.x
                  cache: yarn

            - name: Install packages
              run: yarn install --frozen-lockfile

            - name: Build Vue app
              run: yarn run build

            - name: Add CNAME to dist
              run: |
                cd dist &&
                echo eliasb.be >> CNAME

            - name: Add files to gh-pages branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: dist
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY_SECRET }}
